# Lobby System - SlashLobby
# Made by: Rodrigo R.

# Added on v2.2: For velocity, don't use legacy color formatting ("&c"). Use MiniMessage instead.

server: "lobby" # The server name (Registered on config.yaml of Bungee or velocity.toml)
# The /lobby command will not be available on the following servers
disabled_servers:
  - "auth"

aliases:
  - "hub" # Aliases for the /lobby command (In this example, the /hub command will do the same as the /lobby command)

messages:
  sending: "<green>Sending you to the lobby..."
  already_in_lobby: "<red>You are already in the lobby!"
  disabled: "<red>This command is disabled on this server!"
  error_console: "<red>You cannot execute this command in the console!"
  internal_error: "<red>An internal error has occurred."
  cooldown: "<red>You may use this command again in {time} seconds."
  no_permission: "<red>You don't have permission to execute this command."
  config_reload: "<green>Config reloaded!"

forward_no_permission: true # Forward Players to Lobby if they don't have permission to reload the config

cooldown: # A cooldown before users can use the /lobby command again
  unit: MINUTES # Supported: SECONDS, MINUTES, HOURS, DAYS
  value: 1
  enabled: true

delay: # A delay before users are sent to the lobby
  unit: MINUTES # Supported: SECONDS, MINUTES, HOURS, DAYS
  value: 1
  enabled: false

# Added on v1.4:
titles: # Should the plugin display titles?
  enabled: false
  fadein: 5
  stay: 10
  fadeout: 5
  sending:
    title: "<green>Lobby"
    subtitle: "<green>Sending you to the lobby..."
  cooldown:
    title: "<green>Lobby"
    subtitle: "<green>You may use this command again in {time}."
  already_in_lobby:
    title: "<red>Lobby"
    subtitle: "<red>You are already in the lobby!"
  disabled:
    title: "<red>Lobby"
    subtitle: "<red>This command is disabled on this server!"
  internal_error:
    title: "<red>Lobby"
    subtitle: "<red>An internal error has ocurred."

  # The variable {player} is available on messages (variable for titles removed on v2.2).